# Generated by Django 2.1.7 on 2019-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_info',
            name='profile_pic',
            field=models.ImageField(blank=True, default='#', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='profolio_site',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
